run-dist:
	./build/install/app/bin/app

build:
	./gradlew clean build

clean:
	./gradlew clean

install:
	./gradlew clean install

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

.PHONY: build